Repository ECE493-Group5/adjustable-audio, pull requests merged in 2020-04, with the labels that each got.

#93 quick-fix-stephen
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/hearing_test/HearingTestFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/views/HearingTestView.java
  app/src/main/res/layout/activity_hearing_test.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, hearing test

#95 Merge branch 'master' of https://github.com/ECE493-Group5/adjustable-audio into quick-fix-stephen
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ToneGenerator.java
Labels: bug, hearing test

#108 Implements #94, #96, #97, and #98
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MicrophonePlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/AudioController.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MicrophoneServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/GlobalVolumeListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MicrophoneDataListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/MicrophoneData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MicrophoneService.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MusicService.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/hearing_test/HearingTestResultFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/microphone/MicrophoneFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java
  app/src/main/res/layout/fragment_media_player.xml
  app/src/main/res/layout/fragment_microphone.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, implementation

#111 Some small improvements to conversion algorithm…
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/hearing_test/HearingTestResultFragment.java
Labels: enhancement

#112 Implements minimal speech focus.
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MicrophonePlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MicrophoneService.java
Labels: enhancement

#119 Fix for #114
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MusicServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java
Labels: bug

#121 Merge branch 'master' of https://github.com/ECE493-Group5/adjustable-audio into improvements/bugfixing-stephen
  app/build.gradle
  app/src/main/java/com/ece493/group5/adjustableaudio/HearingTestActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerPreset.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestResult.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/MediaData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ToneData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/storage/Encrypter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/storage/SaveController.java
  app/src/main/java/com/ece493/group5/adjustableaudio/storage/Saver.java
  app/src/main/java/com/ece493/group5/adjustableaudio/views/HearingTestView.java
  app/src/test/java/com/ece493/group5/adjustableaudio/AudioDataUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/EncrypterUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/EqualizerModelUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/EqualizerPresetListControllerUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/EqualizerPresetUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/HearingTestModelUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/HearingTestResultListControllerUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/HearingTestResultUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/JsonizerUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/MediaDataUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/MicrophoneDataUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/SaveControllerUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/SaverUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/SongUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/TimeUtilsUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/ToneDataUnitTest.java
  app/src/test/java/com/ece493/group5/adjustableaudio/ToneGeneratorUnitTest.java
Labels: testing

#122 Test alex
  app/build.gradle
  app/src/androidTest/java/com/ece493/group5/adjustableaudio/MediaPlayerFragmentTest.java
  app/src/androidTest/java/com/ece493/group5/adjustableaudio/MediaQueueViewTest.java
  app/src/androidTest/java/com/ece493/group5/adjustableaudio/MusicNotificationTest.java
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MediaPlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/notifications/MusicNotificationManager.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MusicService.java
  app/src/test/java/com/ece493/group5/adjustableaudio/MediaPlayerAdapterUnitTest.java
Labels: testing
