Repository ECE493-Group5/adjustable-audio, pull requests merged in 2020-03, with the labels that each got.

#59 Added a way to control audio balancing of the MediaPlayer
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MediaPlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MusicServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MediaDataListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MediaSessionListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioDevice.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/MediaData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerViewModel.java
Labels: implementation, media player

#63 Microphone player
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ece493/group5/adjustableaudio/MainActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MediaPlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MicrophonePlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/AudioController.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MicrophoneServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MusicServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/interfaces/IAudioDevice.java
  app/src/main/java/com/ece493/group5/adjustableaudio/interfaces/IServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MediaDataListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MediaSessionListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MicrophoneDataListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioDevice.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ChangableData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerPreset.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/MediaData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/MicrophoneData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MicrophoneService.java
  app/src/main/java/com/ece493/group5/adjustableaudio/services/MusicService.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/microphone/MicrophoneFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java
  app/src/main/res/drawable/ic_microphone_black_24dp.xml
  app/src/main/res/drawable/ic_search_black_24dp.xml
  app/src/main/res/drawable/microphone_toggle_button.xml
  app/src/main/res/drawable/toggle_button_circle.xml
  app/src/main/res/drawable/toggle_button_circle_off.xml
  app/src/main/res/drawable/toggle_button_circle_on.xml
  app/src/main/res/drawable/toggle_button_square.xml
  app/src/main/res/drawable/toggle_button_square_off.xml
  app/src/main/res/drawable/toggle_button_square_on.xml
  app/src/main/res/layout/fragment_microphone.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/menu/equalizer_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: implementation, microphone

#78 Fixes #77 and #75
  app/build.gradle
  app/src/main/java/com/ece493/group5/adjustableaudio/MainActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MicrophoneServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/EqualizerModelListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestResult.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/hearing_test/HearingTestResultFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java
Labels: bug

#80 Implementation for hearing test to equalizer conversion.
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MediaPlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/adapters/MicrophonePlayerAdapter.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/AudioController.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MicrophoneServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/MusicServiceInteractor.java
  app/src/main/java/com/ece493/group5/adjustableaudio/interfaces/IAudioDevice.java
  app/src/main/java/com/ece493/group5/adjustableaudio/listeners/MediaSessionListener.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ApplicationEqualizerPresets.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerPreset.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/hearing_test/HearingTestResultFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java
  app/src/main/res/layout/fragment_media_player.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: enhancement, implementation

#83 Test alex
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/ece493/group5/adjustableaudio/DisclaimerActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/SplashActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/storage/Saver.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_logo_vector.xml
  app/src/main/res/drawable/rectangle_border.xml
  app/src/main/res/font/logo_font_family.xml
  app/src/main/res/font/manteka.ttf
  app/src/main/res/layout/activity_disclaimer.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/raw/disclaimer.txt
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design, enhancement

#84 improvements/bugfixing-stephen
  app/src/main/java/com/ece493/group5/adjustableaudio/HearingTestActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ToneGenerator.java
  app/src/main/java/com/ece493/group5/adjustableaudio/views/HearingTestView.java
  app/src/main/res/layout/activity_hearing_test.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, implementation

#89 fixes #85 and fixes #86
  app/src/main/java/com/ece493/group5/adjustableaudio/controllers/AudioController.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/AudioData.java
  app/src/main/java/com/ece493/group5/adjustableaudio/ui/media_player/MediaPlayerFragment.java
Labels: bug

#92 Merge branch 'master' of https://github.com/ECE493-Group5/adjustable-audio into improvements/bugfixing-stephen
  app/src/main/java/com/ece493/group5/adjustableaudio/HearingTestActivity.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/HearingTestModel.java
  app/src/main/java/com/ece493/group5/adjustableaudio/models/ToneGenerator.java
Labels: bug
